#if more than one preload is desired then continue to preload other backgrounds
preload = /home/vedd/.config/hypr/wallpaper/wallpaper.jpg
wallpaper = DP-1,contain:/home/vedd/.config/hypr/wallpaper/wallpaper.jpg